services:
  validator:
    image: ghcr.io/tplr-ai/basilica/validator:latest
    container_name: basilica-validator
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    privileged: true

    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - /opt/basilica/config/validator.toml:/app/validator.toml:ro
      - /opt/basilica/data:/app/data:rw
      - ~/.ssh:/app/keys:ro
      - ~/.bittensor:/root/.bittensor:rw
      - /var/log/basilica:/var/log/basilica:rw

    ports:
      - "8080:8080"     # Server/API port
      - "9090:9090"     # Metrics port

    networks:
      - basilica_network

    command: ["--config", "/app/validator.toml", "start"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  watchtower:
    image: containrrr/watchtower
    container_name: basilica-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LABEL_ENABLE=true
    command: --label-enable --cleanup --interval 300

networks:
  basilica_network:
    driver: bridge

