services:
  validator:
    image: basilica/validator:latest
    container_name: basilica-validator
    restart: unless-stopped

    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1

    volumes:
      # Configuration
      - ../../validator.toml:/app/validator.toml:ro
      
      # Data persistence
      - /var/lib/basilica:/var/lib/basilica:rw
      - /etc/basilica:/etc/basilica:rw
      
      # SSH keys for validation
      - /etc/ssh:/etc/ssh:ro
      - ~/.ssh:/root/.ssh:ro
      
      # Shared attestor binary access
      - /usr/local/bin/gpu-attestor:/usr/local/bin/gpu-attestor:ro
      
      # Log access
      - /var/log/basilica:/var/log/basilica:rw

    ports:
      - "8080:8080"   # HTTP API
      - "8081:8081"   # Metrics

    networks:
      - basilica_network

    command: ["start", "--config", "/app/validator.toml"]
    
    logging:
      driver: "journald"
      options:
        max-size: "10m"
        max-file: "3"
        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  basilica_network:
    driver: bridge