[package]
name = "basilica-sdk-python"
version = "0.1.0"
edition = "2021"
authors = ["Basilica Team"]
description = "Python bindings for the Basilica SDK"
license = "MIT OR Apache-2.0"

[lib]
name = "basilica"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stub_gen"

[features]
default = []
extension-module = ["pyo3/extension-module"]
stub-gen = ["dep:pyo3-stub-gen", "dep:pyo3-stub-gen-derive"]

[dependencies]
basilica-sdk = { path = "../basilica-sdk" }
basilica-validator = { path = "../basilica-validator", features = [
    "client",
    "openapi",
] }
pyo3 = { workspace = true }
pyo3-stub-gen = { workspace = true, optional = true }
pyo3-stub-gen-derive = { workspace = true, optional = true }
tokio = { workspace = true }
serde = { workspace = true }
pythonize = { workspace = true }

[build-dependencies]
