[service]
environment = "development"
log_level = "info"
metrics_enabled = true
service_id = "test-billing-service"

[server]
grpc_port = 50051
http_port = 8081
metrics_port = 9091

[database]
url = "postgres://billing:billing_dev_password@localhost:5432/basilica_billing"
max_connections = 10
min_connections = 2
connect_timeout_seconds = 30
acquire_timeout_seconds = 30
idle_timeout_minutes = 10
max_lifetime_minutes = 30

[aws]
region = "us-east-1"
use_iam_auth = false

[telemetry]
enabled = true
batch_size = 100
flush_interval_seconds = 30
