# Development miner configuration with skip_registration

[server]
host = "0.0.0.0"
port = 8092

[database]
url = "sqlite:./data/miner.db"
run_migrations = true

[logging]
level = "info"
format = "pretty"

[metrics]
enabled = false

[bittensor]
wallet_name = "test_miner"
hotkey_name = "default"
network = "finney"
netuid = 39
coldkey_name = "default"
axon_port = 8091
# Skip registration for development
skip_registration = true

[validator_comms]
request_timeout = { secs = 30, nanos = 0 }

[validator_comms.auth]
enabled = true
method = "bittensor_signature"

[validator_comms.rate_limit]
enabled = true

[executor_management]
health_check_interval = { secs = 30, nanos = 0 }

[[executor_management.executors]]
id = "dev-executor-1"
name = "Development Executor"
grpc_address = "127.0.0.1:50051"

[security]
enable_mtls = false
jwt_secret = "dev-secret-change-in-production"
verify_signatures = false