# Miner Configuration for Local Subtensor Network

[server]
host = "0.0.0.0"
port = 8092

[database]
url = "sqlite:/tmp/miner.db?mode=rwc"
max_connections = 5
min_connections = 1
connect_timeout = { secs = 5, nanos = 0 }
run_migrations = true

[logging]
level = "debug"
format = "pretty"

[metrics]
enabled = true
host = "0.0.0.0"
port = 9091

[bittensor]
wallet_name = "test_miner"
hotkey_name = "default"
coldkey_name = "default"
network = "local"
netuid = 1  # Default subnet for local testing
chain_endpoint = "ws://subtensor-alice:9944"
axon_port = 8091
# Use localhost for local testing
external_ip = "127.0.0.1"
max_weight_uids = 256
skip_registration = true  # Skip registration for localnet testing

[validator_comms]
request_timeout = { secs = 30, nanos = 0 }
max_concurrent_sessions = 100

[validator_comms.auth]
enabled = false  # Disable auth for local testing
method = "bittensor_signature"

[validator_comms.auth.token_validation]
validate_issuer = true
validate_audience = true
validate_expiration = true
clock_skew_tolerance = { secs = 60, nanos = 0 }

[validator_comms.rate_limit]
enabled = false  # Disable rate limiting for local testing
requests_per_second = 10
burst_capacity = 20
window_duration = { secs = 60, nanos = 0 }

[executor_management]
health_check_interval = { secs = 30 }
health_check_timeout = { secs = 10 }
max_retry_attempts = 3
auto_recovery = true
executors = [
    { id = "local-executor", grpc_address = "executor:50052", name = "Local Executor" }
]

# Remote executor deployment configuration (disabled for localnet)
# [remote_executor_deployment]
# Commented out for localnet to use static executor configuration

[security]
enable_mtls = false
jwt_secret = "localnet-jwt-secret-change-in-production"
token_expiration = { secs = 3600, nanos = 0 }
allowed_validators = []
verify_signatures = false  # Disabled for localnet testing