# Miner configuration for test network

[server]
host = "0.0.0.0"
port = 8092

[database]
url = "sqlite:./data/miner.db"
max_connections = 5
min_connections = 1
run_migrations = true

[logging]
level = "info"
format = "pretty"

[metrics]
enabled = true
[metrics.prometheus]
enabled = true
port = 9091

[bittensor]
wallet_name = "test_miner"
hotkey_name = "default"
network = "test"
netuid = 387
coldkey_name = "default"
axon_port = 8091
# Note: skip_registration is NOT set, so it will try to register on chain

[validator_comms]
request_timeout = { secs = 30, nanos = 0 }
max_concurrent_sessions = 100

[validator_comms.auth]
enabled = true
method = "bittensor_signature"

[validator_comms.rate_limit]
enabled = true
requests_per_second = 10
burst_capacity = 20
window_duration = { secs = 60, nanos = 0 }

[executor_management]
health_check_interval = { secs = 30, nanos = 0 }
health_check_timeout = { secs = 10, nanos = 0 }
max_retry_attempts = 3
auto_recovery = true

[[executor_management.executors]]
id = "test-executor-1"
name = "Test Executor"
grpc_address = "127.0.0.1:50051"

[security]
enable_mtls = false
jwt_secret = "test-secret-change-in-production"
token_expiration = { secs = 3600, nanos = 0 }
allowed_validators = []
verify_signatures = true