# Public API Configuration for Local Network
[server]
host = "0.0.0.0"
port = 8000

[redis]
url = "redis://redis:6379"

[bittensor]
network = "local"
chain_endpoint = "ws://alice:9944"
netuid = 1

# Wallet configuration for public-api
[bittensor.wallet]
name = "public-api"
hotkey = "default"
path = "/home/basilica/.bittensor"

[database]
url = "sqlite:///app/data/public-api.db?mode=rwc"

[logging]
level = "debug"
format = "pretty"

[metrics]
enabled = true
host = "0.0.0.0"
port = 8080