# Validator configuration for test network

[server]
host = "0.0.0.0"
port = 8080

[database]
url = "sqlite:./data/validator.db"
max_connections = 5
min_connections = 1
run_migrations = true

[logging]
level = "info"
format = "pretty"

[metrics]
enabled = true
[metrics.prometheus]
enabled = true
port = 9090

[bittensor]
wallet_name = "validator"
hotkey_name = "default"
network = "test"
netuid = 387
chain_endpoint = "wss://test.finney.opentensor.ai:443"
weight_interval_secs = 300
axon_port = 9091
# external_ip = "your.external.ip.here"  # Optional

[verification]
verification_interval = { secs = 600, nanos = 0 }
max_concurrent_verifications = 50
challenge_timeout = { secs = 120, nanos = 0 }
min_score_threshold = 0.1
min_stake_threshold = 1.0
max_miners_per_round = 20
min_verification_interval = { secs = 1800, nanos = 0 }
netuid = 387

[storage]
data_dir = "./data"

[api]
bind_address = "0.0.0.0:8080"
max_body_size = 1048576
# api_key = "your-api-key-here"  # Optional