"""Parity tests for the vendored PULSE codec (basilica._pulse, #1666).

The NORMATIVE implementation lives in basilica-backend
(python/pulse-verl/src/pulse_verl, contracts doc C2.4-C2.5). The fixtures in
tests/fixtures/pulse_codec_golden.json were generated BY that implementation
(deterministic inputs, no RNG); these tests assert the vendored copy
reproduces them BYTE-FOR-BYTE — a drifted vendor copy fails here before it
can publish artifacts a compliant consumer would reject.
"""

import hashlib
import json
from pathlib import Path

import pytest

torch = pytest.importorskip("torch")
pytest.importorskip("xxhash")
pytest.importorskip("zstandard")

GOLDEN = json.loads(
    (Path(__file__).parent / "fixtures" / "pulse_codec_golden.json").read_text()
)


def _t(vals):
    return torch.tensor(vals, dtype=torch.bfloat16)


def _base_state():
    return {"w.a": _t([[0.0, 1.0], [2.0, 3.0]]), "w.b": _t([1.5, -2.5, 0.0])}


def _new_state():
    return {"w.a": _t([[0.0, 1.25], [2.0, 3.0]]), "w.b": _t([1.5, -2.5, 7.0])}


def test_digests_match_the_normative_implementation():
    from basilica._pulse.codec import Snapshot
    from basilica._pulse.digest import format_digest, tensor_digest

    base = _base_state()
    assert format_digest(tensor_digest(base["w.a"])) == GOLDEN["tensorDigest_w.a"]
    assert Snapshot(dict(base)).digest() == GOLDEN["stateDigest_base"]


def test_patch_bytes_match_the_normative_implementation():
    # Byte-for-byte: same inputs -> the SAME envelope pulse_verl produced,
    # including header JSON ordering and zstd framing.
    from basilica._pulse.codec import ModelMeta, Snapshot

    snap = Snapshot(_base_state())
    anchor_digest = snap.digest()
    meta = ModelMeta(id="test@deadbeef", digest=anchor_digest, param_count=snap.param_count())
    patch, sdig = snap.encode_step(
        _new_state().items(),
        step=1,
        base_step=0,
        model=meta,
        base_state_digest=anchor_digest,
    )
    snap.commit_step()
    assert sdig == GOLDEN["stateDigest_after_patch"]
    assert hashlib.sha256(patch).hexdigest() == GOLDEN["patch_sha256"]
    assert patch.hex() == GOLDEN["patch_hex"]


def test_the_golden_patch_applies_and_verifies():
    # The consumer half: pulse_verl's own bytes reconstruct the new state
    # through the vendored apply path, digest gate included (I3).
    from basilica._pulse.codec import Snapshot, parse_patch

    consumer = Snapshot(_base_state())
    parsed = parse_patch(bytes.fromhex(GOLDEN["patch_hex"]))
    applied_digest = consumer.apply_patch(parsed)
    assert applied_digest == GOLDEN["stateDigest_after_patch"]
    assert consumer.digest() == GOLDEN["stateDigest_after_patch"]


def test_anchor_roundtrip_preserves_digest(tmp_path):
    pytest.importorskip("safetensors")
    from basilica._pulse.anchor import load_anchor, save_anchor
    from basilica._pulse.codec import Snapshot

    snap = Snapshot(_base_state())
    path = tmp_path / "anchor.safetensors"
    digest = save_anchor(snap, path, step=7)
    assert digest == GOLDEN["stateDigest_base"]
    loaded, step, loaded_digest = load_anchor(path)
    assert (step, loaded_digest) == (7, digest)
    assert loaded.digest() == digest
