{
 "title": "Basilica Validator Logs",
 "tags": [
  "basilica",
  "validator",
  "logs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "validator_uid", "label": "Validator UID", "query": "204" },
   { "name": "netuid", "label": "Net UID", "query": "39" },
   { "name": "search_text", "label": "Search Text", "query": "rental" },
   { "name": "log_level", "label": "Log Level", "query": "debug,info,warn,error" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# <img width=50 class=\"logo\" alt=\"BASILICA logo\" src=\"https://www.synapz.org/assets/basilica/basilica_logo200x200.png\"> Basilica - Sacred Compute\n\n<p align=\"center\">\n  <a href=\"https://github.com/tplr-ai/basilica/tree/main/docs\">Docs</a> • \n  <a href=\"https://github.com/tplr-ai/basilica/blob/main/docs/quickstart.md\">Quick Start</a> • \n  <a href=\"https://github.com/tplr-ai/basilica/blob/main/docs/architecture.md\">Architecture</a>\n</p>\n\n---\n\n```bash\n$ curl -sSL https://basilica.ai/install.sh | bash\n```\n"
   }
  },
  {
   "title": "Total Validated GPU Servers in the Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (executor_id, gpu_model) (basilica_validator_executor_gpu_count > 0))",
     "legendFormat": "Total GPUs"
    }
   ]
  },
  {
   "title": "GPUs by Type/Model",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (gpu_model) (count by (executor_id, gpu_model) (basilica_validator_executor_gpu_count))",
     "legendFormat": "{{gpu_model}}"
    }
   ]
  },
  {
   "title": "Executors per Miner by GPU Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count by (miner_uid, gpu_model) (max by (executor_id, gpu_model, miner_uid) (basilica_validator_executor_gpu_count > 0))"
    }
   ]
  },
  {
   "title": "GPUs per Executor (with Miner)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "max by (executor_id, gpu_model, miner_uid) (basilica_validator_executor_gpu_count > 0)"
    }
   ]
  },
  {
   "title": "Miner Performance Table",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(basilica_validator_miner_successful_validations[24h])"
    },
    {
     "expr": "increase(basilica_validator_miner_successful_validations[1h])"
    }
   ]
  },
  {
   "title": "Successful Validations per miner",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "basilica_validator_miner_successful_validations"
    },
    {
     "expr": "increase(basilica_validator_miner_successful_validations[24h])"
    }
   ]
  },
  {
   "title": "Miners by Weight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(500, max by (miner_uid) (basilica_validator_miner_weight{miner_uid!=\"204\"}))\r\n",
     "legendFormat": "Miner {{miner_uid}}"
    }
   ]
  },
  {
   "title": "Log Count per Validator UID per Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "sum by(validator_uid, level) (rate({source=\"docker\", netuid=\"$netuid\"} |= `` | logfmt | __error__ = \"\" [1m]))"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 49, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{source=\"docker\", netuid=\"$netuid\", validator_uid=\"$validator_uid\"} |= `` |~ `$search_text` | logfmt"
    }
   ]
  }
 ]
}