version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: basilica-payments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments_dev_password
      POSTGRES_DB: basilica_payments
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - payments_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - basilica_payments_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments -d basilica_payments"]
      interval: 10s
      timeout: 5s
      retries: 5

  payments:
    build:
      context: ../..
      dockerfile: scripts/payments/Dockerfile
    container_name: basilica-payments-dev
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://payments:payments_dev_password@postgres:5432/basilica_payments
      - SUBXT_WS=wss://entrypoint-finney.opentensor.ai:443
      - BILLING_GRPC=http://host.docker.internal:50051
      - PAYMENTS_GRPC_BIND=0.0.0.0:50061
      - SS58_PREFIX=42
      - TAO_DECIMALS=9
      - PAYMENTS_AEAD_KEY_HEX=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - TAO_USD_RATE=450.0
    volumes:
      - ../../config/payments.dev.toml:/app/payments.toml:ro
      - ../../crates:/app/crates:ro
      - ../../Cargo.toml:/app/Cargo.toml:ro
      - ../../Cargo.lock:/app/Cargo.lock:ro
    ports:
      - "50061:50061"  # gRPC port (different from billing)
      - "8082:8082"    # HTTP port (8082 to avoid conflict with billing/validator)
      - "9092:9092"    # Metrics port (different from billing)
    networks:
      - basilica_payments_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  payments_postgres_data:
    driver: local

networks:
  basilica_payments_network:
    driver: bridge
